from .anime_screen import AnimeScreenController
from .crashlog_screen import CrashLogScreenController
from .downloads_screen import DownloadsScreenController
from .help_screen import HelpScreenController
from .home_screen import HomeScreenController
from .my_list_screen import MyListScreenController
from .search_screen import SearchScreenController
