<StreamDialogLabel@MDLabel>:
    adaptive_height:True
    max_lines:0
    shorten:False
    markup:True
    font_style: "Label"
    role: "medium"
    bold:True
<StreamDialogHeaderLabel@MDLabel>:
    adaptive_height:True
    halign:"center"
    max_lines:0
    shorten:False
    bold:True
    markup:True
    font_style: "Title"
    role: "medium"
    md_bg_color:self.theme_cls.secondaryContainerColor
    padding:"10dp"



<AnimdlStreamDialog>
    md_bg_color:self.theme_cls.backgroundColor
    radius:8
    size_hint:None,None
    height:"500dp"
    width:"400dp"
    MDBoxLayout:
        spacing: '10dp'
        padding:"10dp"
        orientation:"vertical"
        StreamDialogHeaderLabel:
            text:"Stream on Animdl"
        StreamDialogLabel:
            text:"Title"
        MDTextField:
            id:title_field
            required:True
        StreamDialogLabel:
            text:"Range"
        MDTextField:
            id:range_field
            required:True
        StreamDialogLabel:
            text:"Latest"
        MDTextField:
            id:latest_field
            required:True
        StreamDialogLabel:
            text:"Quality"
        MDTextField:
            id:quality_field
            required:True
        MDBoxLayout:
            orientation:"vertical"
            MDButton:
                pos_hint: {'center_x': 0.5}
                on_press:root.stream_anime(app)
                MDButtonIcon:
                    icon:"rss"
                MDButtonText:
                    text:"Stream"