#:import get_hex_from_color kivy.utils.get_hex_from_color

<CharactersHeaderText@MDLabel>    
    adaptive_height:True
    # halign:"center"
    max_lines:0
    shorten:False
    md_bg_color:self.theme_cls.secondaryContainerColor
    bold:True
    markup:True
    font_style: "Body"
    role: "large"
    padding:"10dp"

<CharactersContainer@MDBoxLayout>:
    adaptive_height:True
    md_bg_color:self.theme_cls.surfaceContainerLowColor
    padding:"10dp"
    orientation:"vertical"

<CharacterText@MDLabel>:
    adaptive_height:True
    max_lines:0
    shorten:False
    markup:True
    font_style: "Body"
    role: "small"

<CharacterHeader@MDBoxLayout>:
    adaptive_height:True
    spacing:"10dp"
<CharacterAvatar@FitImage>
    radius:50
    size_hint:None,None
    height:"50dp"
    width:"50dp"

<CharacterSecondaryContainer@MDBoxLayout>:
    adaptive_height:True
    orientation:"vertical"
<AnimeCharacter>:
    spacing:"5dp"
    adaptive_height:True
    orientation:"vertical"
    CharacterHeader:
        padding:"10dp"
        CharacterAvatar:
            source:root.character["image"]
        CharacterText:
            text: root.character["name"]
            pos_hint:{"center_y":.5}
    
    CharacterSecondaryContainer:
        spacing:"5dp"
        MDDivider:
        CharacterText:
            text: "Details"
        MDDivider:
        CharacterText:
            text:"[color={}]Gender:[/color] {}".format(get_hex_from_color(self.theme_cls.primaryColor),root.character["gender"])
        CharacterText:
            text:"[color={}]Date Of Birth:[/color] {}".format(get_hex_from_color(self.theme_cls.primaryColor),root.character["dateOfBirth"])
        CharacterText:
            text:"[color={}]Age:[/color] {}".format(get_hex_from_color(self.theme_cls.primaryColor),root.character["age"])
        CharacterText:
            text:"[color={}]Description:[/color] {}".format(get_hex_from_color(self.theme_cls.primaryColor),root.character["description"])
            max_lines:5
        CharacterText:
            text:"[color={}]Voice Actors:[/color] {}".format(get_hex_from_color(self.theme_cls.primaryColor),root.voice_actors["name"])
        MDDivider:


<AnimeCharacters>:
    adaptive_height:True
    container:container
    orientation:"vertical"
    CharactersHeaderText:
        text:"Characters"
    CharactersContainer:
        id:container
        
        
