<Controls>
    adaptive_height:True
    padding:"10dp"
    spacing:"10dp"
    pos_hint: {'center_x': 0.5}
    MDButton:
        on_press: print("presed")
        MDButtonText:
            text:"Add to MyList"
    MDButton:
        on_press: 
            if root.screen:root.screen.stream_anime_with_custom_cmds_dialog()
        MDButtonText:
            text:"Watch on Animdl"
    MDButton:
        on_press: app.watch_on_allanime(root.screen.data["title"]["romaji"])
        MDButtonText:
            text:"Watch on AllAnime"
