<Controls@MDBoxLayout>
    adaptive_height:True
    padding:"10dp"
    spacing:"10dp"
    pos_hint: {'center_x': 0.5}
    MDButton:
        on_press: print("presed")
        MDButtonText:
            text:"Add to MyList"
    MDButton:
        on_press: print("presed")
        MDButtonText:
            text:"Watch on Animdl"
    MDButton:
        on_press: print("presed")
        MDButtonText:
            text:"Watch on AllAnime"
