# <DescriptionHeader>   
#     adaptive_height:True
#     md_bg_color:self.theme_cls.secondaryContainerColor
#     MDLabel:
#         text:root.text
#         adaptive_height:True
#         max_lines:0
#         shorten:False
#         bold:True
#         font_style: "Body"
#         role: "large"
#         padding:"10dp"

<DescriptionContainer@MDBoxLayout>:
    adaptive_height:True
    md_bg_color:self.theme_cls.surfaceContainerLowColor
    padding:"10dp"

<DescriptionText@MDLabel>:
    adaptive_height:True
    max_lines:0
    shorten:False
    markup:True
    font_style: "Body"
    role: "small"
<AnimeDescription>:
    orientation:"vertical"
    adaptive_height:True
    HeaderLabel:
        halign:"left"
        text:"Description"
    DescriptionContainer:
        DescriptionText:
            text:root.description
        
            