<AnimeHeader>:
    adaptive_height:True
    orientation: 'vertical'
    MDBoxLayout:
        adaptive_height:True
        md_bg_color:self.theme_cls.secondaryContainerColor
        MDLabel:
            text: root.titles
            adaptive_height:True
            padding:"5dp"
            bold:True
            shorten:False
            max_lines:2
            font_style:"Label"
            role:"large"
    FitImage:
        size_hint_y: None
        height: dp(250)
        source:root.banner_image
    