#:set yellow [.9,.9,0,.9]

<RankingsLabel@MDLabel>:
    max_lines:0
    shorten:False
    # padding:"10dp"
    markup:True
    font_style: "Label"
    role: "medium"
<RankingsHeaderLabel@MDLabel>:
    color:self.theme_cls.primaryColor
    bold:True
    # padding:"10dp"
    max_lines:0
    shorten:False
    markup:True
    font_style: "Label"
    role: "large"



<RankingsDivider@MDDivider>:
    orientation:"vertical"

<RankingsBoxLayout@MDBoxLayout>:
    orientation:"vertical"
    padding:"20dp"
<RankingsBar>:
    size_hint_y:None
    height:dp(100)
    line_color:self.theme_cls.secondaryColor
    padding:"10dp"
    RankingsBoxLayout:
        size_hint_x:.4
        RankingsHeaderLabel:
            text:"Average Score"
        MDBoxLayout:
            adaptive_width:True
            MDBoxLayout:
                adaptive_size:True
                # spacing:"5dp"
                pos_hint: {'center_y': .5}
                MDIcon:
                    icon: "star"
                    color:yellow
                    disabled: not((root.rankings["AverageScore"]/100)*6>=2)
                MDIcon:
                    color:yellow
                    disabled: not(root.rankings["AverageScore"]/100*6>=3)
                    icon: "star"
                MDIcon:
                    color:yellow
                    disabled: not(root.rankings["AverageScore"]/100*6>=4)
                    icon: "star"
                MDIcon:
                    color:yellow
                    disabled: not(root.rankings["AverageScore"]/100*6>=5)
                    icon: "star"
                MDIcon:
                    color:yellow
                    icon: "star"
                    disabled: not(root.rankings["AverageScore"]/100*6>=6)
            RankingsLabel:
                adaptive_width:True
                text: '{}'.format(root.rankings["AverageScore"]/10)
    RankingsDivider:
    RankingsBoxLayout:
        size_hint_x:.3
        RankingsHeaderLabel:
            text:"Popularity"
        RankingsLabel:
            text: '{}'.format(root.rankings["Popularity"])
    RankingsDivider:
    RankingsBoxLayout:
        size_hint_x:.3
        RankingsHeaderLabel:
            text:"Favourites"
        RankingsLabel:
            text: '{}'.format(root.rankings["Favourites"])
    
    