#:import get_hex_from_color kivy.utils.get_hex_from_color

<ReviewHeaderText@MDLabel>    
    adaptive_height:True
    # halign:"center"
    max_lines:0
    shorten:False
    md_bg_color:self.theme_cls.secondaryContainerColor
    bold:True
    markup:True
    font_style: "Body"
    role: "large"
    padding:"10dp"

<ReviewContainer@MDBoxLayout>:
    adaptive_height:True
    md_bg_color:self.theme_cls.surfaceContainerLowColor
    padding:"10dp"
    orientation:"vertical"

<ReviewText@MDLabel>:
    adaptive_height:True
    max_lines:0
    shorten:False
    markup:True
    font_style: "Body"
    role: "small"

<ReviewHeader@MDBoxLayout>:
    adaptive_height:True
    spacing:"10dp"
    padding:"10dp"

<ReviewerAvatar@FitImage>
    radius:50
    size_hint:None,None
    height:"50dp"
    width:"50dp"

<AnimeReview>
    orientation:"vertical"
    adaptive_height:True
    ReviewHeader:
        ReviewerAvatar:
            source:root.review["avatar"]
        ReviewText:
            pos_hint: {'center_y': 0.5}
            text:root.review["username"]
    MDDivider:
    ReviewText:
        text:root.review["summary"]
    MDDivider:
<AnimeReviews>:
    container:container
    adaptive_height:True
    orientation:"vertical"
    ReviewHeaderText:
        text:"reviews"
    ReviewContainer:
        id:container