<MediaCard>
    adaptive_height:True
    spacing:"5dp"
    size_hint_x: None
    width:dp(100)
    height: dp(150)
    FitImage:
        source:root.cover_image_url
        fit_mode:"fill"
        size_hint: None, None
        width: dp(100)
        height: dp(150)
    MDDivider:
        color:root.theme_cls.primaryColor if root._trailer_url else [0.5, 0.5, 0.5, 0.5] 
        size_hint: None, 1
        width: dp(100)
    SingleLineLabel:
        font_style:"Label"
        role:"medium"
        text:root.title
        max_lines:2        
        halign:"center"
        color:self.theme_cls.secondaryColor
        size_hint_x: None
        shorten:True
        width: dp(100)

