#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import StringProperty kivy.properties.StringProperty

<HelpCard@MDBoxLayout>
    spacing:"10dp"
    orientation:"vertical"
    adaptive_height:True
    md_bg_color:self.theme_cls.surfaceContainerLowColor
    theme_text_color:"Secondary"

<HelpHeaderLabel@HeaderLabel>
    halign:"left"

<HelpDescription@MDLabel>:
    adaptive_height:True
    max_lines:0
    shorten:False
    markup:True
    font_style: "Body"
    padding:"10dp"
    role: "large"

<HelpScreenView>
    md_bg_color: self.theme_cls.backgroundColor
    # main_container:main_container
    MDBoxLayout:
        NavRail:
            screen:root
        MDAnchorLayout:
            anchor_y: 'top'
            padding:"10dp"
            MDBoxLayout:
                orientation: 'vertical'
                SearchBar:
                MDScrollView:
                    size_hint_x:.95
                    MDBoxLayout:
                        adaptive_height:True
                        padding:"10dp"
                        orientation:"vertical"
                        HelpCard:
                            HelpHeaderLabel:
                                text:"Animdl Commands"
                            HelpDescription:
                                text:root.animdl_help
                        HelpCard:
                            HelpHeaderLabel:
                                text:"Installing Animdl"
                            HelpDescription:
                                text:root.installing_animdl_help
                        HelpCard:
                            HelpHeaderLabel:
                                text:"Available Themes"
                            HelpDescription:
                                text:root.available_themes
                        HelpCard:
                            HelpHeaderLabel:
                                text:"About"
                            HelpDescription:
                                text:"This app was made to be a gui wrapper for any and all anime cli tools. Inoder to solve the age old problem of getting the same experience from the cli as you would in a website"