<AnimeBoxLayout@MDBoxLayout>:
    adaptive_height:True
    orientation:'vertical'

<AnimeLabel@MDLabel>:
    adaptive_height:True
    bold:True

<AnimeScreenView>:
    md_bg_color: self.theme_cls.backgroundColor
    MDBoxLayout:
        orientation: 'vertical'
        MDBoxLayout:
            adaptive_height:True
            MDIconButton:
                icon:"arrow-left"
                on_press:root.manager_screens.current = root.caller_screen_name
            MDTextField:
                on_text_validate: 
                    root.update_current_link(self)
            
        VideoPlayer:
            source:root.current_link
        AnimeBoxLayout:
            AnimeLabel:
                text:"Sub"
            MDSegmentedButton:
                id:pl
                multiselect:False
                MDSegmentedButtonItem:
                    on_active:
                        pl.selected_segments = [self]
                        root.update_current_video_stream("gogoanime")
                    MDSegmentButtonLabel:
                        text:"GoGoAnime"
                MDSegmentedButtonItem:
                    on_active:
                        root.update_current_video_stream("dropbox")
                        pl.selected_segments = [self]
                    MDSegmentButtonLabel:
                        text:"DropBox"
                MDSegmentedButtonItem:
                    on_active:
                        root.update_current_video_stream("sharepoint")
                        pl.selected_segments = [self]
                    MDSegmentButtonLabel:
                        text:"Share Point"
                MDSegmentedButtonItem:
                    on_active:
                        root.update_current_video_stream("wetransfer")
                        pl.selected_segments = [self]
                    MDSegmentButtonLabel:
                        text:"weTransfer"

