<AnimeBoxLayout@MDBoxLayout>:
    adaptive_height:True
    orientation:'vertical'

<AnimeLabel@MDLabel>:
    adaptive_height:True
    bold:True

<EpisodeButton>:
    pos_hint:{"center_y":0.5,"center_x":0.5}
    on_press:root.change_episode_callback(root.text)
    radius: 10
    MDButtonText:
        text:root.text



<AnimeScreenView>:
    md_bg_color: self.theme_cls.backgroundColor
    episodes_container:episodes_container
    video_player:video_player
    is_dub:is_dub
    MDBoxLayout:
        padding:"10dp"
        orientation: 'vertical'
        MDBoxLayout:
            adaptive_height:True
            MDIconButton:
                icon:"arrow-left"
                on_press:root.manager_screens.current = root.caller_screen_name
           
        MDBoxLayout:
            VideoPlayer:
                id:video_player
                source:root.current_link
        AnimeBoxLayout:
            padding: "20dp"
            radius:5
            spacing:"10dp"
            md_bg_color: self.theme_cls.surfaceContainerLowColor
            AnimeBoxLayout:
                orientation:'horizontal'
                MDIconButton:
                    icon:"skip-previous"
                    on_press:root.previous_episode()
                MDIconButton:
                    icon:"skip-next"
                    on_press: root.next_episode()
                MDIconButton:
                    icon:"download"
                    on_press: 
                        if root.current_link: app.download_anime_video(root.current_link,(root.current_title[0],root.current_episode))
                MDButton:
                    on_press: 
                        if root.current_link: app.play_on_mpv(root.current_link)
                    MDButtonText:
                        text:"Play on MPV"
                AnimeLabel:
                    text:"Dub: "
                    padding: "10dp"
                    adaptive_width:True
                MDSwitch:
                    id:is_dub
            AnimeBoxLayout:
                AnimeLabel:
                    text:"servers: "
                MDSegmentedButton:
                    id:pl
                    multiselect:False
                    MDSegmentedButtonItem:
                        on_active:
                            pl.selected_segments = [self]
                            root.update_current_video_stream("gogoanime")
                        MDSegmentButtonLabel:
                            text:"GoGoAnime"
                    MDSegmentedButtonItem:
                        id:dropbox
                        on_active:
                            root.update_current_video_stream("dropbox")
                            pl.selected_segments = [self]
                        MDSegmentButtonLabel:
                            text:"DropBox"
                    MDSegmentedButtonItem:
                        on_active:
                            root.update_current_video_stream("sharepoint")
                            pl.selected_segments = [self]
                        MDSegmentButtonLabel:
                            text:"Share Point"
                    MDSegmentedButtonItem:
                        on_active:
                            root.update_current_video_stream("wetransfer")
                            pl.selected_segments = [self]
                        MDSegmentButtonLabel:
                            text:"weTransfer"
            MDDivider:

            MDRecycleView:
                id: episodes_container
                size_hint_y:None
                height:"50dp"
                key_viewclass:"viewclass"
                RecycleBoxLayout:
                    size_hint: None,1
                    key_size:"width"
                    spacing:"10dp"
                    width:self.minimum_width
                    default_size_hint:0,0
                    default_size:30,30
                    default_pos_hint:{"center_y":0.5,"center_x":0.5}
                     
