<MyListScreenView>
    md_bg_color: self.theme_cls.backgroundColor
    user_anime_list_container:user_anime_list_container
    MDBoxLayout:
        size_hint:1,1
        NavRail:
            screen:root
        MDAnchorLayout:
            anchor_y: 'top'
            padding:"10dp"
            size_hint:1,1
            MDBoxLayout:
                spacing:"40dp"
                orientation: 'vertical'
                size_hint:.95,1
                SearchBar:
                MDRecycleView:
                    pos_hint:{"center_x":.5}
                    size_hint:1,1
                    id:user_anime_list_container
                    key_viewclass:"viewclass"
                    MDRecycleGridLayout:
                        pos_hint: {'center_x': 0.5}
                        spacing: '40dp'
                        padding: "25dp","50dp","75dp","200dp"
                        default_size_hint:None,None
                        default_size:dp(100),dp(150)
                        cols:3 if root.width <= 1100 else 5
                        size_hint_y:None
                        height:max(self.parent.parent.height,self.minimum_height)

    
