<SearchScreenView>
    md_bg_color: self.theme_cls.backgroundColor
    search_results_container:search_results_container
    trending_anime_sidebar:trending_anime_sidebar
    search_results_pagination:search_results_pagination
    filters:filters
    MDBoxLayout:
        size_hint:1,1
        NavRail:
            screen:root
        MDAnchorLayout:
            anchor_y: 'top'
            padding:"10dp"
            size_hint:1,1

            MDBoxLayout:
                orientation: 'vertical'
                size_hint:1,1
                SearchBar:
                MDBoxLayout:
                    spacing:"20dp"
                    padding:"75dp","10dp","100dp","0dp"
                    MDBoxLayout:
                        orientation: 'vertical'
                        size_hint:1,1
                        Filters:
                            id:filters
                        MDBoxLayout:
                            spacing:"20dp"
                            MDScrollView:
                                size_hint:1,1
                                MDBoxLayout:
                                    orientation: 'vertical'
                                    size_hint_y:None
                                    height:self.minimum_height
                                    MDGridLayout:
                                        pos_hint: {'center_x': 0.5}
                                        id:search_results_container
                                        spacing: '40dp'
                                        padding: "75dp","50dp","75dp","200dp"
                                        cols:5
                                        size_hint_y:None
                                        height:self.minimum_height
                                    SearchResultsPagination:
                                        id:search_results_pagination
                                        search_view:root
                    MDBoxLayout:
                        orientation:"vertical"
                        size_hint_y:1
                        size_hint_x:None
                        width: dp(250)
                        MDLabel:
                            text:"Trending"
                            adaptive_height:True
                            halign:"center"
                            max_lines:0
                            # md_bg_color:Stat
                            shorten:False
                            bold:True
                            font_style: "Label"
                            role: "large"
                            padding:"10dp"
                        MDScrollView:
                            TrendingAnimeSideBar:
                                id:trending_anime_sidebar
