#:import color_text fastanime.Utility.kivy_markup_helper.color_text

<TaskText@MDLabel>:
    adaptive_height:True
    max_lines:0
    shorten:False
    markup:True
    font_style: "Label"
    role: "large"
    bold:True


<TaskCard>:
    adaptive_height:True
    radius:8
    padding:"20dp"
    md_bg_color:self.theme_cls.surfaceContainerHighColor

    TaskText:
        size_hint_x:.8
        text:"{} Episode: {}".format(root.file[0],root.file[1])
    

