#:import get_hex_from_color kivy.utils.get_hex_from_color

#:set yellow [.9,.9,0,.9]

# overides and customization
<MDLabel>:
    adaptive_height:True
    max_lines:1
    valign:"top"
    shorten_from:"right"
    shorten:True

<MDLabelShortened@MDLabel>
    bold:True
<MDIcon>
    valign:"center"


<MDBoxLayout>:
    # adaptive_height:True
    size_hint_y:None
    height:self.minimum_height


# custom components
<Tooltip>
    MDTooltipPlain:
        text:root.tooltip_text


# <TooltipMDIconButton>


<MediaPopup>
    size_hint: None, None
    height: dp(500)
    width: dp(400)
    radius:[5,5,5,5]
    md_bg_color:self.theme_cls.backgroundColor
    anchor_y: 'top'
    player:player
    MDBoxLayout:
        orientation: 'vertical'
        adaptive_height:False
        anchor_y: 'top'
        MDRelativeLayout:
            size_hint_y: None
            height: dp(250)
            line_color:root.caller.has_trailer_color
            line_width:2
            MediaPopupVideoPlayer:
                id:player
                source:root.caller.trailer_url
                preview:root.caller.preview_image
                state:"play" if root.caller.trailer_url else "stop"
                fit_mode:"fill"
                size_hint_y: None
                height: dp(250)
            MDBoxLayout:
                padding: "10dp","5dp"
                spacing:"5dp"
                pos_hint: {'left': 1,'top': 1}
                adaptive_height:True
                MDIcon:
                    icon: "star"
                    color:yellow
                    disabled: not(root.caller.stars[0])
                MDIcon:
                    color:yellow
                    disabled: not(root.caller.stars[1])
                    icon: "star"
                MDIcon:
                    color:yellow
                    disabled: not(root.caller.stars[2])
                    icon: "star"
                MDIcon:
                    color:yellow
                    disabled: not(root.caller.stars[3])
                    icon: "star"
                MDIcon:
                    color:yellow
                    icon: "star"
                    disabled: not(root.caller.stars[4])
                MDIcon:
                    color: yellow
                    icon: "star"
                    disabled: not(root.caller.stars[5])

                MDLabel:
                    text: f"{root.caller.episodes} Episodes"
                    halign:"right"
                    font_style:"Label"
                    role:"medium"
                    bold:True
                    pos_hint: {'center_y': 0.5}
                    adaptive_height:True
                    color: 0,0,0,.7
            
            MDBoxLayout:
                padding:"5dp"
                pos_hint: {'bottom': 1}
                adaptive_height:True
                MDLabel:
                    text:root.caller.media_status
                    opacity:.8
                    halign:"left"
                    font_style:"Label"
                    role:"medium"
                    bold:True
                    pos_hint: {'center_y': .5}
                    adaptive_height:True
                MDLabel:
                    text:root.caller.first_aired_on
                    opacity:.8
                    halign:"right"
                    font_style:"Label"
                    role:"medium"
                    bold:True
                    pos_hint: {'center_y': .5}
                    adaptive_height:True
        MDBoxLayout:
            orientation: 'vertical'
            padding:"10dp"
            spacing:"10dp"
            adaptive_height:False
            MDBoxLayout:
                adaptive_height:True
                MDBoxLayout:
                    adaptive_height:True
                    pos_hint: {'center_y': 0.5}
                    TooltipMDIconButton:
                        tooltip_text:root.caller.title
                        icon: "play-circle"
                        on_press: root.caller.is_play
                    MDIconButton:
                        icon: "plus-circle" if not(root.caller.is_in_my_list) else "check-circle"
                        on_release:
                            root.caller.is_in_my_list = not(root.caller.is_in_my_list)
                            self.icon = "plus-circle" if not(root.caller.is_in_my_list) else "check-circle"
                    MDIconButton:
                        icon: "bell-circle" if not(root.caller.is_in_my_notify) else "bell-check"
                MDBoxLayout:
                    orientation: 'vertical'
                    pos_hint: {'center_y': 0.5}
                    adaptive_height:True
                    MDLabelShortened:
                        font_style:"Label"
                        role:"small"
                        text: f"[color={get_hex_from_color(self.theme_cls.primaryColor)}]"+"Genres: "+"[/color]"+root.caller.genres
                        markup:True
                    MDBoxLayout:
                        adaptive_height:True
                        MDLabelShortened:
                            font_style:"Label"
                            role:"small"
                            markup:True
                            text: f"[color={get_hex_from_color(self.theme_cls.primaryColor)}]"+"Popularity: "+"[/color]"+root.caller.popularity
                        MDLabelShortened:
                            font_style:"Label"
                            markup:True
                            role:"small"
                            text: f"[color={get_hex_from_color(self.theme_cls.primaryColor)}]"+"Favourites: "+"[/color]"+root.caller.favourites
            MDScrollView:
                size_hint:1,1
                do_scroll_y:True
                MDLabel:
                    font_style:"Body"
                    role:"small"
                    text:root.caller.description
                    shorten:False
                    adaptive_height:True
                    # shorten_from:"right"
                    max_lines:0

            MDBoxLayout:
                orientation: 'vertical'
                adaptive_height:True
                MDLabelShortened:
                    font_style:"Label"
                    role:"small"
                    markup:True
                    text: f"[color={get_hex_from_color(self.theme_cls.primaryColor)}]"+"Author: "+"[/color]"+root.caller.author
                MDLabelShortened:
                    font_style:"Label"
                    markup:True
                    role:"small"
                    text: f"[color={get_hex_from_color(self.theme_cls.primaryColor)}]"+"Studios: "+"[/color]"+root.caller.studios
                MDLabelShortened:
                    font_style:"Label"
                    markup:True
                    role:"small"
                    text: f"[color={get_hex_from_color(self.theme_cls.primaryColor)}]"+"Characters: "+"[/color]"+root.caller.characters
                MDLabelShortened:
                    font_style:"Label"
                    markup:True
                    role:"small"
                    text: f"[color={get_hex_from_color(self.theme_cls.primaryColor)}]"+"Tags: "+"[/color]"+root.caller.tags
            
<MediaCard>
    spacing:"5dp"
    image:"https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx163270-oxwgbe43Cpog.jpg"
    on_release:
        self.open()
    size_hint_x: None
    width:dp(100)
    # height:self.minimum_height
    FitImage:
        source:root.cover_image_url
        fit_mode:"fill"
        size_hint: None, None
        width: dp(100)
        height: dp(150)
    MDDivider:
        color:root.has_trailer_color
    MDLabel:
        font_style:"Label"
        role:"medium"
        text:root.title
        max_lines:2        
        halign:"center"
        color:self.theme_cls.secondaryColor

<MediaCardsContainer>
    # adaptive_height:True
    # size_hint_y:None
    size_hint_x:1
    # height:dp(300)  
    size_hint_y:None
    height:max(self.minimum_height,dp(350),container.minimum_height)
    # adaptive_height:True
    # width:self.minimum_width
    container:container
    orientation: 'vertical'
    padding:"10dp"
    spacing:"5dp"
    MDLabel:
        text:root.list_name
    MDScrollView:
        # do_scroll_x:True
        # do_scroll_y:False
        size_hint:1,None
        height:container.minimum_height
        MDBoxLayout:
            id:container
            padding:"0dp","10dp","100dp","10dp"
            size_hint:None,None
            height:self.minimum_height 
            width:self.minimum_width
            spacing:"10dp"
