<MediaCard>
    adaptive_height:True
    spacing:"5dp"
    image:"https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx163270-oxwgbe43Cpog.jpg"
    size_hint_x: None
    width:dp(100)
    on_release:
        self.open()
    FitImage:
        source:root.cover_image_url
        fit_mode:"fill"
        size_hint: None, None
        width: dp(100)
        height: dp(150)
    MDDivider:
        color:root.has_trailer_color
    SingleLineLabel:
        font_style:"Label"
        role:"medium"
        text:root.title
        max_lines:2        
        halign:"center"
        color:self.theme_cls.secondaryColor

