<PaginationLabel@MDLabel>:
    max_lines:0
    shorten:False
    adaptive_height:True
    font_style: "Label"
    pos_hint:{"center_y":.5}
    halign:"center"
    role: "medium"

<SearchResultsPagination>:
    md_bg_color:self.theme_cls.surfaceContainerLowColor
    radius:8
    adaptive_height:True
    MDIconButton:
        icon:"arrow-left"
        on_release:root.search_view.previous_page()
    PaginationLabel:
        text:"Page {} of {}".format(root.current_page,root.total_pages)
    MDIconButton:
        icon:"arrow-right"
        on_release:root.search_view.next_page()