<TrendingAnimeSideBar>:
    md_bg_color:self.theme_cls.surfaceContainerLowColor
    padding:"25dp","25dp","25dp","200dp"
    pos_hint: {'center_x': 0.5}
    key_viewclass:"viewclass"
    size_hint: None,1 
    width:"250dp"
    pos_hint: {'center_x':.5}
    RecycleBoxLayout:
        orientation: 'vertical'
        key_size:"height"
        key_viewclass:"viewclass"
        pos_hint: {'center_x': 0.8}
        size_hint:None,None
        default_size_hint:None, None
        default_pos_hint:{"center_x":0.8}
        default_size:dp(150),dp(100)
        width:"250dp"
        spacing:"10dp"
        height:max(self.minimum_height,500)
#padding:"0dp","10dp","100dp","10dp"
       # height:max(self.parent.parent.height,self.minimum_height+100)

