<FilterDropDown>:
    MDDropDownItemText:
        text: root.text

<FilterLabel@MDLabel>:
    adaptive_width:True

<Filters>:
    adaptive_height:True
    spacing:"10dp"
    size_hint_x:.95
    pos_hint:{"center_x":.5}
    padding:"10dp"
    md_bg_color:self.theme_cls.surfaceContainerLowColor

    FilterLabel:
        text:"Sort By"
    FilterDropDown:
        id:sort_filter
        text:root.filters["sort"]
        on_release: root.open_filter_menu(self,"sort")
    FilterLabel:
        text:"Status"
    FilterDropDown:
        id:status_filter
        text:root.filters["status"]
        on_release: root.open_filter_menu(self,"status")
