<MyListScreenView>
    md_bg_color: self.theme_cls.backgroundColor
    my_list_container:my_list_container
    MDBoxLayout:
        size_hint:1,1
        NavRail:
            screen:root
        MDAnchorLayout:
            anchor_y: 'top'
            padding:"10dp"
            size_hint:1,1

            MDBoxLayout:
                orientation: 'vertical'
                id:p
                size_hint:1,1
                SearchBar:
                MDScrollView:
                    size_hint:1,1
                    MDGridLayout:
                        spacing: '10dp'
                        padding: "75dp","50dp","10dp","100dp"
                        id:my_list_container
                        cols:5
                        size_hint_y:None
                        height:self.minimum_height

    