<CommonNavigationRailItem>
    MDNavigationRailItemIcon:
        icon:root.icon 
    MDNavigationRailItemLabel:
        text: root.text 


<NavRail>:
    anchor:"top"
    type: "labeled"
    md_bg_color: self.theme_cls.secondaryContainerColor
    MDNavigationRailFabButton:
        icon: "home" 
        on_press: 
            root.screen.manager_screens.current = "home screen"
    CommonNavigationRailItem:
        icon: "magnify"
        text: "Search"
        on_press: 
            root.screen.manager_screens.current = "search screen"

    CommonNavigationRailItem:
        icon: "bookmark" 
        text: "MyList"
        on_press: 
            root.screen.manager_screens.current = "my list screen"
    CommonNavigationRailItem:
        icon: "download-circle"
        text: "Downloads"
        on_press:
            root.screen.manager_screens.current = "downloads screen"
    CommonNavigationRailItem:
        icon: "cog"
        text: "settings"
        on_press:app.open_settings()
