#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import StringProperty kivy.properties.StringProperty

<DownloadsScreenLabel@MDLabel>:
    adaptive_height:True
    max_lines:0
    shorten:False
    markup:True
    font_style: "Label"
    role: "large"
    bold:True
<DownloadsScreenView>
    md_bg_color: self.theme_cls.backgroundColor
    main_container:main_container
    download_progress_label:download_progress_label
    progress_bar:progress_bar
    MDBoxLayout:
        NavRail:
            screen:root
        MDAnchorLayout:
            anchor_y: 'top'
            MDBoxLayout:
                orientation: 'vertical'
                SearchBar:
                MDScrollView:
                    size_hint:.95,1
                    MDGridLayout:
                        padding: "75dp","50dp","10dp","100dp"
                        spacing:"40dp"
                        id:main_container
                        cols:5
                        adaptive_height:True
                MDBoxLayout:
                    size_hint_y:None
                    height:"40dp"
                    spacing:"10dp"
                    padding:"10dp"
                    md_bg_color:self.theme_cls.secondaryContainerColor
                    DownloadsScreenLabel:
                        id:download_progress_label
                        size_hint_x: .6
                        text:"current episode"
                        pos_hint: {'center_y': .5}
                    MDLinearProgressIndicator:
                        id: progress_bar
                        size_hint_x: .4
                        size_hint_y:None
                        height:"10dp"
                        type: "determinate"
                        pos_hint: {'center_y': .5}
