<SearchScreenView>
    md_bg_color: self.theme_cls.backgroundColor
    search_results_container:search_results_container
    trending_anime_sidebar:trending_anime_sidebar
    search_results_pagination:search_results_pagination
    filters:filters
    MDBoxLayout:
        size_hint:1,1
        NavRail:
            screen:root
        MDAnchorLayout:
            anchor_y: 'top'
            padding:"10dp"
            size_hint:1,1

            MDBoxLayout:
                orientation: 'vertical'
                size_hint:1,1
                SearchBar:
                MDBoxLayout:
                    spacing:"20dp"
                    padding:"75dp","10dp","100dp","0dp"
                    MDBoxLayout:
                        orientation: 'vertical'
                        size_hint:1,1
                        Filters:
                            id:filters
                        MDBoxLayout:
                            spacing:"20dp"
                            MDScrollView:
                                size_hint:1,1
                                MDBoxLayout:
                                    orientation: 'vertical'
                                    size_hint_y:None
                                    height:max(self.parent.parent.height,self.minimum_height)
                                    MDRecycleView:
                                        id:search_results_container
                                        key_viewclass:"viewclass"
                                        MDRecycleGridLayout:
                                            pos_hint: {'center_x': 0.5}
                                            spacing: '40dp'
                                            padding: "25dp","50dp","75dp","200dp"
                                            default_size_hint:None,None
                                            default_size:dp(100),dp(150)
                                            cols:3 if root.width <= 1100 else 5
                                            size_hint_y:None
                                            height:max(self.parent.parent.height,self.minimum_height)
                                    SearchResultsPagination:
                                        id:search_results_pagination
                                        search_view:root
                                           
                    MDBoxLayout:
                        orientation:"vertical"
                        size_hint_y:1
                        size_hint_x:None
                        width: dp(250)
                        HeaderLabel:
                            text:"Trending"
                            halign:"center"
                        #TrendingAnimeSideBar:
                         #   id:trending_anime_sidebar

                        MDRecycleView:
                            id:trending_anime_sidebar
                            key_viewclass:"viewclass"
                            MDRecycleGridLayout:
                                md_bg_color:self.theme_cls.surfaceContainerLowColor
                                pos_hint: {'center_x': 0.5}
                                spacing: '40dp'
                                padding: "75dp","25dp","25dp","200dp"
                                default_size_hint:None,None
                                default_pos_hint:{"center_x":0.5,"center_y":0.5}
                                default_size:dp(100),dp(150)
                                cols:1
                                size_hint_y:None
                                height:max(self.parent.parent.height,self.minimum_height)
