from .animdl_stream_dialog import AnimdlStreamDialog
from .characters import AnimeCharacters
from .controls import Controls
from .description import AnimeDescription
from .download_anime_dialog import DownloadAnimeDialog
from .header import AnimeHeader
from .rankings_bar import RankingsBar
from .review import AnimeReviews
from .side_bar import AnimeSideBar
