<Controls>
    adaptive_height:True
    padding:"10dp"
    spacing:"10dp"
    pos_hint: {'center_x': 0.5}
    cols:3
    MDButton:
        on_press:
            root.screen.add_to_user_anime_list()
            add_to_user_list_label.text = "Added to MyAnimeList"
        MDButtonText:
            id:add_to_user_list_label
            text:"Add to MyAnimeList"
    MDButton:
        on_press: 
            if root.screen:root.screen.stream_anime_with_custom_cmds_dialog()
        MDButtonText:
            text:"Watch on Animdl"
    MDButton:
        on_press: 
            if root.screen:root.screen.stream_anime_with_custom_cmds_dialog(mpv=True)
        MDButtonText:
            text:"Watch on mpv"
    MDButton:
        on_press: app.watch_on_allanime(root.screen.data["title"]["romaji"]) if root.screen.data["title"]["romaji"] else app.watch_on_allanime(root.screen.data["title"]["english"])
        MDButtonText:
            text:"Watch on AllAnime"
    MDButton:
        on_press: 
            if root.screen:root.screen.open_download_anime_dialog()
        MDButtonText:
            text:"Download Anime"
